/**
 * @module hooks
 * @description Fastify lifecycle hooks for structured, consolidated per-request logging.
 *
 * Pattern — "consolidate logs at creation time":
 * Rather than emitting separate "request received" and "request completed" logs,
 * we accumulate context throughout the request lifecycle and emit ONE log per
 * request in the onResponse hook. This makes it trivial to filter by any field
 * (url + status, p99 latency, userId) without join logic across multiple records.
 *
 * Hook responsibilities:
 *   onRequest   — capture start time; seed logContext with fields known at start
 *   preHandler  — add user context once JWT has been verified (if applicable)
 *   onResponse  — emit the single canonical structured log for this request
 *   onError     — capture error context into logContext; also log immediately so
 *                 errors are visible even if onResponse never fires
 *
 * OTel field naming follows HTTP semantic conventions:
 * https://opentelemetry.io/docs/specs/semconv/http/http-spans/
 */
import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';

// ---------------------------------------------------------------------------
// Fastify type augmentations
// ---------------------------------------------------------------------------

declare module 'fastify' {
  interface FastifyRequest {
    /**
     * High-resolution start time captured in onRequest via process.hrtime.bigint().
     * Nanosecond precision; used to compute http.duration_ms in onResponse.
     */
    startTime: bigint;

    /**
     * Accumulated log fields built up across the request lifecycle.
     * onRequest seeds the object; preHandler and onError enrich it;
     * onResponse spreads it into the final structured log line.
     */
    logContext: Record<string, unknown>;
  }
}

// ---------------------------------------------------------------------------
// Hook implementations
// ---------------------------------------------------------------------------

/**
 * onRequest hook — runs first in the lifecycle for every request.
 *
 * Seeds the two request-scoped properties used throughout the lifecycle:
 *   - startTime: high-resolution BigInt timestamp for accurate duration calculation
 *   - logContext: accumulator for all fields that will appear in the response log
 *
 * @param {FastifyRequest} req
 * @param {FastifyReply} _reply - Unused at this stage.
 */
async function onRequestHook(
  req: FastifyRequest,
  _reply: FastifyReply
): Promise<void> {
  // Nanosecond-precision start time. process.hrtime.bigint() is monotonic and
  // unaffected by system clock adjustments — safer than Date.now() for durations.
  req.startTime = process.hrtime.bigint();

  // Seed with everything we know at request start. Additional fields are
  // appended by preHandler (user context) and onError (error context).
  req.logContext = {
    'http.method': req.method,
    'http.url': req.url,
    // requestId is generated by Fastify's genReqId — UUID v4 in production,
    // fixed string in tests. Propagated into every log line for correlation.
    requestId: req.id,
  };
}

/**
 * preHandler hook — runs after all schema validation, before route handler.
 *
 * By the time a global preHandler fires, any hooks that ran earlier in the
 * onRequest stage (including user-context injection tests inject) have already
 * populated req.user if the caller set it there. For routes protected by
 * verifyJWT (added as a route-level preHandler), user context is available
 * when this hook is opportunistically checked.
 *
 * Never logs the email address — userId is an opaque identifier sufficient
 * for tracing "which user triggered this error" without logging PII.
 *
 * @param {FastifyRequest} req
 * @param {FastifyReply} _reply - Unused at this stage.
 */
async function preHandlerHook(
  req: FastifyRequest,
  _reply: FastifyReply
): Promise<void> {
  if (req.user?.userId) {
    req.logContext['user.id'] = req.user.userId;
  }
}

/**
 * onResponse hook — emits the single consolidated log for this request.
 *
 * Called after the response has been sent. By this point logContext contains
 * everything accumulated across the lifecycle (method, url, requestId, userId,
 * and — for errored requests — error context added by the onError hook).
 *
 * Spreading logContext into the log call merges all accumulated fields into
 * one flat JSON record, making it trivial to filter by any dimension.
 *
 * @param {FastifyRequest} req
 * @param {FastifyReply} reply
 */
async function onResponseHook(
  req: FastifyRequest,
  reply: FastifyReply
): Promise<void> {
  const durationNs = process.hrtime.bigint() - req.startTime;
  // Convert nanoseconds → milliseconds as a floating-point number.
  const durationMs = Number(durationNs) / 1_000_000;

  req.log.info(
    {
      ...req.logContext,
      'http.status_code': reply.statusCode,
      'http.duration_ms': durationMs,
    },
    'request completed'
  );
}

/**
 * onError hook — captures error context and emits an immediate error log.
 *
 * Two responsibilities:
 *   1. Enrich logContext with error metadata so the consolidated onResponse log
 *      also contains error information (for one-stop request inspection).
 *   2. Emit an immediate error-level log entry so errors are surfaced even if
 *      onResponse somehow never fires (e.g. connection reset before reply).
 *
 * @param {FastifyRequest} req
 * @param {FastifyReply} _reply - Unused; errors are already handled by errorHandler.
 * @param {Error} error - The unhandled error caught by Fastify.
 */
async function onErrorHook(
  req: FastifyRequest,
  _reply: FastifyReply,
  error: Error
): Promise<void> {
  // Add error metadata to the accumulator so onResponse log carries it too.
  req.logContext['error.type'] = error.constructor.name;
  req.logContext['error.message'] = error.message;
  // AppError subclasses expose a statusCode; include it when present.
  req.logContext['error.statusCode'] = (
    error as Record<string, unknown>
  ).statusCode;

  // Immediate error log — for cases where the error is interesting on its own
  // or where onResponse may not fire (e.g. premature connection close).
  req.log.error(
    {
      ...req.logContext,
      err: error,
    },
    'request error'
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Registers all lifecycle hooks on the Fastify instance.
 *
 * Call this once during app setup, before registering any routes.
 * The hooks are application-scoped and fire for every request regardless
 * of which route handles it.
 *
 * @param {FastifyInstance} app - The Fastify application instance.
 */
export function registerHooks(app: FastifyInstance): void {
  app.addHook('onRequest', onRequestHook);
  app.addHook('preHandler', preHandlerHook);
  app.addHook('onResponse', onResponseHook);
  app.addHook('onError', onErrorHook);
}
